// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using Apex.Units;
using Apex;


namespace UnitScripts
{
	public class BasicUnit : MonoBehaviour
	{
		public Transform exit;
		public float exitThreshold = 5f;
		void Start()
		{

			UnitFacade u = (UnitFacade) this.GetUnitFacade();
			GameObject exit = GameObject.Find("CreepExit");
			u.MoveTo(exit.transform.position,false);
		}

		public void Update() {
			if(exit!=null) {
				if(Vector3.Distance(exit.position,this.transform.position)<exitThreshold) {
					Destroy(this.gameObject);
				}
			}
		}
		
	}
}

