// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnitScripts;
using UnityEngine;


namespace CreepSpawnerPackage
{
	[System.Serializable]
	public class WaveUnits
	{
		public GameObject unitPrefab;
		public float timeBetweenSpawn;
		private float _countToNextUnit=-1f;
		public float healthMultiplier;
		public string spawnLocation = "CreepSpawner";
		public string exitLocation = "CreepExit";
		public int creepCount;
		public GameObject spawnLocationObj;
		public WaveUnits ()
		{
		}
		
		public void processUnits() {
			if(_countToNextUnit<0f) {
				_countToNextUnit = timeBetweenSpawn;
				if(spawnLocationObj==null) {
					spawnLocationObj = GameObject.Find (spawnLocation);
				}
			}
			_countToNextUnit -= Time.deltaTime;
			if(_countToNextUnit<0f) {
		
				GameObject u = (GameObject) GameObject.Instantiate(unitPrefab.gameObject,spawnLocationObj.transform.position,spawnLocationObj.transform.rotation);
				u.GetComponent<BasicUnit>().exit = GameObject.Find(exitLocation).transform;
				creepCount--;
			}
		}
		
	}
}

